---
- name: Deploy app from branch on dev-server
  hosts: dev_server
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ci_registry_image: "{{ lookup('env','CI_REGISTRY_IMAGE') }}"
    ci_commit_ref_name: "{{ lookup('env','CI_COMMIT_REF_NAME') }}"
    ci_registry: "{{ lookup('env','CI_REGISTRY') }}"
    ci_registry_user: "{{ lookup('env','CI_REGISTRY_USER') }}"
    ci_job_token: "{{ lookup('env','CI_JOB_TOKEN') }}"
  tasks:
    - name: Debug vars
      debug:
        msg: |
          ci_registry_image: {{ ci_registry_image }}
          ci_commit_ref_name: {{ ci_commit_ref_name }}
          ci_registry: {{ ci_registry }}
          ci_registry_user: {{ ci_registry_user }}
          ci_job_token: {{ ci_job_token }}
    - name: Login to gitlab docker registry
      docker_login:
        username: "{{ ci_registry_user }}"
        password: "{{ ci_job_token }}"
        state: present
        #debug: false
        registry_url: "{{ ci_registry }}"
    - name: Deploy reddit-app
      docker_compose:
        project_name: reddit
        debug: yes
        definition:
          version: "3.3"
          services:
            post_db:
              image: mongo:3.2
              volumes:
                - post_db:/data/db
              networks:
                - reddit_back
            comment_db:
              image: mongo:3.2
              volumes:
                - comment_db:/data/db
              networks:
                - reddit_back
            ui:
              image: "{{ ci_registry_image }}/ui:{{ ci_commit_ref_name }}"
              ports:
                - 9292:9292
              networks:
                - reddit_front
            post:
              image: "{{ ci_registry_image }}/post:{{ ci_commit_ref_name }}"
              networks:
                - reddit_front
                - reddit_back
            comment:
              image: "{{ ci_registry_image }}/comment:{{ ci_commit_ref_name }}"
              networks:
                - reddit_front
                - reddit_back

          volumes:
            post_db:
            comment_db:

          networks:
            reddit_front:
            reddit_back:

      register: output

    - debug:
        var: output

    - assert:
        that:
          - "post_db.reddit_post_db_1.state.running"
          - "post.reddit_post_1.state.running"
          - "comment.reddit_comment_1.state.running"
          - "ui.reddit_ui_1.state.running"
