version: "3.3"
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - reddit_back
  ui:
    build: ./ui
    image: ${USERNAME}/ui:1.0
    ports:
      - 9292:9292/tcp
    networks:
      - reddit_front
  post:
    build: ./post-py
    image: ${USERNAME}/post:1.0
    networks:
      - reddit_front
      - reddit_back
  comment:
    build: ./comment
    image: ${USERNAME}/comment:1.0
    networks:
      - reddit_front
      - reddit_back

volumes:
  post_db:

networks:
  reddit_front:
  reddit_back:
