version: "3.3"
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      - reddit_back
  ui:
    environment:
      APP_HOME: ${UI_APP_HOME}
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - reddit_front
  post:
    environment:
      APP_HOME: ${POST_APP_HOME}
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - reddit_front
      - reddit_back
  comment:
    environment:
      APP_HOME: ${COMMENT_APP_HOME}
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - reddit_front
      - reddit_back

volumes:
  post_db:

networks:
  reddit_front:
  reddit_back:
